version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main/run.py
    restart: always
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      dbmate:
        condition: service_started
    labels:
      - autoheal=true

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6535819169DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/migration" up
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:6535819169DB@db:5432/postgres?sslmode=disable

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
