version: "3.3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main/main.py
    volumes:
      - .:/code
    links:
      - db
      - dbmate
    depends_on:
      db:
          condition: service_healthy
      dbmate:
          condition: service_completed_successfully
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6535819169DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  dbmate:
    image: amacneil/dbmate
    command: -d "/code/migration" up
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:6535819169DB@db:5432/postgres?sslmode=disable
